irregular_nouns = {'child': 'children', 
                   'goose': 'geese', 
                   'man': 'men',
                   'woman': 'women',
                   'superman': 'supermen',
                   'superwoman': 'superwomen',
                   'tooth': 'teeth',
                   'foot': 'feet',
                   'mouse': 'mice',
                   'person': 'poeple',
                   'ox': 'oxen',
                   'louse': 'lice',
                   'alumna': 'alumnae',
                   'charisma': 'charismata'}

# https://dictionary.cambridge.org/grammar/british-grammar/nouns-singular-and-plural?q=Singular+and+plural+nouns
# https://usefulenglish.ru/writing/irregular-plural-nouns
nouns_in_plurals = ['sheep', 'series', 'species', 'deer',
                    'bison', 'moose', 'swine', 'fish', 
                    'dozen', 'aircraft', 'means', 'corps', 
                    'headquarters', 'crossroads', 'alms', 
                    'gallows', 'barracks', 'classics', 'economics', 'maths', 
                    'linguistics', 'mathematics', 'physics', 'aerobics', 'phonetics',
                    'politics', 'statistics', 'acoustics', 
                    'acrobatics', 'gymnastics', 'measles', 'mumps',
                    'news', 'binoculars', 'headphones', 'sunglasses',
                    'glasses', 'scissors', 'tweezers', 'pantyhose',
                    'jeans', 'pyjamas', 'tights', 'knickers',
                    'shorts', 'trousers', 'pants', 'belongings', 'slacks',
                    'breeches', 'pagamas', 'clothes', 'congratulations',
                    'briefs', 'panties', 'pliers', 'earnings', 'goods',
                    'tongs', 'pincers', 'forceps', 'spectacles', 
                    'likes', 'dislikes', 'outskirts', 'premises',
                    'buildings', 'savings', 'money', 'stairs',
                    'surroundings', 'thanks', 'audience', 'public',
                    'arms', 'troops', 'weapons', 'remains',
                    'billiards', 'chess', 'checkers', 'cards', 'dominoes',]